name: 'Sentry Release Action'
description: 'GitHub Action for send releases to Sentry'
author: 'dmandrade'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  version:
    description: 'Version tag'
    default: ''
  environment:
    description: 'Deploy environment to associate with release'
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
