name: 'Sentry Release Action'
description: 'GitHub Action for send releases to Sentry'
author: 'dmandrade'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  auth-token:
    description: 'The authentication token to use for all communication with Sentry'
    default: ''
  url:
    description: 'The URL to use to connect to sentry. This defaults to https://sentry.io/'
    default: 'https://sentry.io/'
  org:
    description: 'The slug of the organization to use for a command'
    default: ''
  project:
    description: 'The slug of the project to use for a command'
    default: ''
  version:
    description: 'Version tag'
    default: ''
  environment:
    description: 'Deploy environment to associate with release'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
